{"uuid": "10acffe9-f83c-41af-aaf2-13863de35fee", "children": ["8f16aa1c-9040-4420-aaf3-aad5b6b5366f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\conftest.py\", line 18, in driver\n    driver = webdriver.Firefox()\n             ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 62, in __init__\n    self.service.start()\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 106, in start\n    if self.is_connectable():\n       ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 123, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\Desktop\\Diplom_Vlada_Filippova_10\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlada\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 845, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1730442932220, "stop": 1730442933496}], "start": 1730442932220, "stop": 1730442934593}